/*
 * Copyright (C)
 */

#ifndef KARGATUM_COMPILERDEFS_H
#define KARGATUM_COMPILERDEFS_H

#define KARGATUM_PLATFORM_WINDOWS 0
#define KARGATUM_PLATFORM_UNIX    1
#define KARGATUM_PLATFORM_APPLE   2
#define KARGATUM_PLATFORM_INTEL   3

// must be first (win 64 also define _WIN32)
#if defined( _WIN64 )
#  define KARGATUM_PLATFORM KARGATUM_PLATFORM_WINDOWS
#elif defined( __WIN32__ ) || defined( WIN32 ) || defined( _WIN32 )
#  define KARGATUM_PLATFORM KARGATUM_PLATFORM_WINDOWS
#elif defined( __APPLE_CC__ )
#  define KARGATUM_PLATFORM KARGATUM_PLATFORM_APPLE
#elif defined( __INTEL_COMPILER )
#  define KARGATUM_PLATFORM KARGATUM_PLATFORM_INTEL
#else
#  define KARGATUM_PLATFORM KARGATUM_PLATFORM_UNIX
#endif

#define KARGATUM_COMPILER_MICROSOFT 0
#define KARGATUM_COMPILER_GNU       1
#define KARGATUM_COMPILER_BORLAND   2
#define KARGATUM_COMPILER_INTEL     3

#ifdef _MSC_VER
#  define KARGATUM_COMPILER KARGATUM_COMPILER_MICROSOFT
#elif defined( __BORLANDC__ )
#  define KARGATUM_COMPILER KARGATUM_COMPILER_BORLAND
#elif defined( __INTEL_COMPILER )
#  define KARGATUM_COMPILER KARGATUM_COMPILER_INTEL
#elif defined( __GNUC__ )
#  define KARGATUM_COMPILER KARGATUM_COMPILER_GNU
#  define GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
#else
#  error "FATAL ERROR: Unknown compiler."
#endif

#endif
